[package]
name = "wnfs"
version = "0.1.10"
description = "WebNative filesystem core implementation"
keywords = ["wnfs", "webnative", "ipfs", "decentralisation"]
categories = [
  "filesystem",
  "cryptography",
  "web-programming",
  "wasm",
]
license = "Apache-2.0"
readme = "README.md"
edition = "2021"
repository = "https://github.com/wnfs-wg/rs-wnfs/tree/main/wnfs"
homepage = "https://fission.codes"
authors = ["The Fission Authors"]

[dependencies]
aes-gcm = "0.10"
anyhow = "1.0"
async-once-cell = "0.4"
async-recursion = "1.0"
async-std = { version = "1.11", features = ["attributes"] }
async-stream = "0.3"
async-trait = "0.1"
bitvec = { version = "1.0", features = ["serde"] }
chrono = { version = "0.4", default-features = false, features = ["clock", "std"] }
futures = "0.3"
futures-util = "0.3"
hashbrown = "0.13"
lazy_static = "1.4"
libipld = { version = "0.15", features = ["dag-cbor", "derive", "serde-codec"] }
log = "0.4"
proptest = { version = "1.0", optional = true }
rand_core = "0.6"
semver = { version = "1.0", features = ["serde"] }
serde = { version = "1.0", features = ["rc"] }
sha3 = "0.10"
skip_ratchet = { version = "0.1", features = ["serde"] }
thiserror = "1.0"
xxhash-rust = { version = "0.8", features = ["xxh3"] }

[dev-dependencies]
env_logger = "0.10"
proptest = "1.0"
rand = "0.8"
test-log = "0.2"
test-strategy = "0.2"

[lib]
name = "wnfs"
path = "src/lib.rs"

[features]
default = []
wasm = []
test_strategies = ["proptest"]
