[package]
name = "wnfslib-android"
version = "0.1.0"
edition = "2021"

[lib]
name = "wnfslib"
crate-type = ["cdylib", "staticlib"]

[dependencies]
wnfs = "0.1.9"
wnfs_utils = { git = "https://github.com/hhio618/wnfs-utils" }
serde = "1.0.147"
serde_json = "1.0.87"
chrono = "0.4.22"
crc32fast = "1.3.2"
env_logger = "0.9.0"
log = "0.4.14"
image = "0.24.2"
url = { version = "2.2.2", features = ["serde"] }
openssl = { version = "0.10.35", features = ["vendored"] }
tokio = { version = "1", features = ["full"] }
rand = "0.8.5"
libipld = "0.14.0"
kv = "0.24.0"

[target.'cfg(target_os="android")'.dependencies]
jni = { version = "0.19.0", default-features = false }
android_logger = "0.11.0"
ndk = "0.6.0"
