[package]
name = "wnfslib-android"
version = "0.1.0"
edition = "2021"

[lib]
name = "wnfslib"
crate-type = ["cdylib", "staticlib"]

[dependencies]
wnfs = "0.1.7"
crc32fast = "1.3.2"
env_logger = "0.9.0"
log = "0.4.14"
image = "0.24.2"
url = { version = "2.2.2", features = ["serde"] }
openssl = { version = "0.10.35", features = ["vendored"] }

[target.'cfg(target_os="android")'.dependencies]
jni = { version = "0.19.0", default-features = false }
android_logger = "0.11.0"
ndk = "0.6.0"
