[package]
name = "wnfslib-android"
version = "0.1.0"
edition = "2021"

[lib]
name = "wnfslib"
crate-type = ["cdylib", "staticlib"]

[dependencies]
wnfs = {path = "../dep/wnfs" }
wnfsutils = {path = "../dep/wnfsutils" }
anyhow = "1.0.66"
serde = "1.0.149"
serde_json = "1.0.89"
chrono = "0.4.22"
crc32fast = "1.3.2"
env_logger = "0.9.0"
log = "0.4.14"
image = "0.24.2"
url = { version = "2.2.2", features = ["serde"] }
openssl = { version = "0.10.35", features = ["vendored"] }
tokio = { version = "1", features = ["full"] }
rand = "0.8.5"
libipld = { version = "0.15", features = ["dag-cbor", "derive", "serde-codec"] }
kv = "0.24.0"


jni = { version = "0.19.0", default-features = false }
android_logger = "0.11.0"
ndk = "0.6.0"
